version: '3.8'

services:
  db:
    image: mariadb:10
    container_name: db_lamp
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  web:
    build: .
    container_name: apache2
    restart: always
    depends_on:
      - db
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    environment:
      MYSQL_DB_HOST: db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "1200:80"
    environment:
      - MYSQL_DB_HOST=db
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

volumes:
  db_data:

env_file:
  - .env
